name: Build-CI

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}
    
    name: Build-${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: List environment
      run: |
        echo "Runtime Environment" && env | sort
    - name: cmake version
      run: |
        cmake --version
        cmake --help
        gcc --version
    - name: List build files
      run: |
        echo "Current User" && id
        echo "Current Directory" && pwd
        echo "Directory Listing - Current Directory" && ls -lhR ${PWD}
    - name: cmake build
      run: bash ./build.sh
    - name: run tests
      run: bash ./test.sh
