name: Build-CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}

    name: Build-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: List environment
        run: |
          echo "Runtime Environment" && env | sort
        shell: bash
      - name: cmake version
        run: |
          cmake --version
          which gcc && echo gcc && gcc --version
          which gcc-8 && echo gcc-8 && gcc-8 --version
          which gcc-9 && echo gcc-9 && gcc-9 --version
          which gcc-10 && echo gcc-10 && gcc-10 --version
          which clang && echo clang && clang --version
          which clang-9 && echo clang-9 && clang-9 --version
          which clang-10 && echo clang-10 && clang-10 --version
          which c++ && c++ --version
      - name: List build files
        run: |
          echo "Current User" && id
          echo "Current Directory" && pwd
          echo "Directory Listing - Current Directory" && ls -lhR ${PWD}
        shell: bash
      - name: cmake build
        run: bash ./build.sh
      - name: Run tests
        run: bash -c "./test.sh --verbose"
      - name: Test program execution
        run: ./cmake-build/blist blist_version.h
