name: Build-CI

on: push

strategy:
  matrix:
    os: [ 'ubuntu-latest', 'macOS-latest' ]
name: os-${{ matrix.os }}

jobs:
  build-${{ matrix.os }}:
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: List environment
      run: |
        echo "Runtime Environment" && env | sort
    - name: cmake version
      run: |
        cmake --version
        cmake --help
        gcc --version
    - name: List build files
      run: |
        echo "Current User" && id
        echo "Current Directory" && pwd
        echo "Directory Listing - Current Directory" && ls -lhR ${PWD}
    - name: cmake build
      run: bash ./build.sh
    - name: run tests
      run: bash ./test.sh
