name: Build-CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    name: Build-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: List environment
        run: |
          echo "Runtime Environment" && env | sort
        shell: bash
      - name: cmake version
        run: |
          cmake --version
          which gcc && echo gcc && gcc --version
          which clang-9 && echo clang-9 && clang-9 --version
          which clang-10 && echo clang-10 && clang-10 --version
          c++ --version
      - name: List build files
        run: |
          echo "Current User" && id
          echo "Current Directory" && pwd
          echo "Directory Listing - Current Directory" && ls -lhR ${PWD}
        shell: bash
      - name: cmake build
        run: bash ./build.sh
      - name: run tests
        run: bash -c "./test.sh --verbose"
