---
name: Lint Code Base

# https://github.com/marketplace/actions/super-linter
# https://github.com/github/super-linter
# https://github.com/super-linter/super-linter

# Run the linter job for all pull requests
on: pull_request

permissions:
  actions: read

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
